### ISSUE TITLE
Authentication Required

### ISSUE THREAD

**Issue by ghost** [Fluidbyte/Codiad-Terminal#2]
I installed Codiad-Terminal in plugins folder.
I activated it trough Plugins option.
It appears in the side panel.

But when I click it, the emulator asks me to enter a password.
I don't know how to handle this.

Regards,

**Comment by ShraddhaPW** [comment]
sudo command is not working in this terminal. Please help

**Comment by ShraddhaPW** [comment]
I also want SSH to work in my codiad terminal
