### ISSUE TITLE
404 Error when opening the terminal

### ISSUE THREAD

**Issue by daroganadir** [Fluidbyte/Codiad-Terminal#3]
Hello,

I installed the plugin and tried to start the terminal. But I am getting a 404 when calling this URL while loading the terminal

 http://[mydomain.tld]/[BASEPATH TO CODIAD]/plugins/Codiad-Terminal-master/emulator/index.php?id=kd9kdi8nundj

Since the BASEPATH includes the absolute path to my codiad installation, the terminal can not be loaded. I tried to change the basepath in the config.php of codiad, but then the ide is not be loaded anymore.

I guess I just configured something wrong. Can you help me ?

Thanks!
Nadir.

**Comment by patgrosse** [comment]
I had the same problem, probably reproducable when using the Codiad docker image from [wernight/codiad](https://hub.docker.com/r/wernight/codiad/).

I resolved the problem by using the Javascript provided path instead of the absolute file system paths (?) used in BASE_PATH. See PR #24
